// <auto-generated />
namespace VADS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RefactoringVehicleModelBrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefactoringVehicleModelBrand));
        
        string IMigrationMetadata.Id
        {
            get { return "201312130612417_RefactoringVehicleModelBrand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
