// <auto-generated />
namespace VADS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class holAKAC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(holAKAC));
        
        string IMigrationMetadata.Id
        {
            get { return "201312132235200_holAKAC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
