// <auto-generated />
namespace VADS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixingInvitation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingInvitation));
        
        string IMigrationMetadata.Id
        {
            get { return "201312132125343_FixingInvitation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
