// <auto-generated />
namespace VADS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updatedUsersandMore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedUsersandMore));
        
        string IMigrationMetadata.Id
        {
            get { return "201312050430377_updatedUsersandMore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
