// <auto-generated />
namespace VADS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class VehicleModelForenkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VehicleModelForenkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201312130716439_VehicleModelForenkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
